DROP FUNCTION dbstats_reset_format(integer, integer, integer);
DROP FUNCTION dbstats_reset_format_diff(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION wal_stats_reset_format(integer, integer, integer);
DROP FUNCTION wal_stats_reset_format_diff(integer, integer, integer, integer, integer);
