DROP FUNCTION dbstats_reset_format(integer, integer, integer);
DROP FUNCTION dbstats_reset_format_diff(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION wal_stats_reset_format(integer, integer, integer);
DROP FUNCTION wal_stats_reset_format_diff(integer, integer, integer, integer, integer);
DROP FUNCTION get_report_context;
DROP FUNCTION profile_checkavail_statements_jit_stats;
DROP FUNCTION profile_checkavail_statements_temp_io_times;
DROP FUNCTION profile_checkavail_top_temp;
DROP FUNCTION profile_checkavail_stmt_wal_bytes;
DROP FUNCTION profile_checkavail_planning_times;
DROP FUNCTION profile_checkavail_sessionstats;
DROP FUNCTION profile_checkavail_io_times;
DROP FUNCTION profile_checkavail_tbl_top_dead;
DROP FUNCTION profile_checkavail_tbl_top_mods;
DROP FUNCTION profile_checkavail_functions;
DROP FUNCTION profile_checkavail_trg_functions;
DROP FUNCTION profile_checkavail_rusage;
DROP FUNCTION profile_checkavail_rusage_planstats;
