DROP FUNCTION dbstats_reset_format(integer, integer, integer);
DROP FUNCTION dbstats_reset_format_diff(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_io_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer);
DROP FUNCTION cluster_stat_slru_reset_format(integer, integer, integer, integer, integer);
DROP FUNCTION wal_stats_reset_format(integer, integer, integer);
DROP FUNCTION wal_stats_reset_format_diff(integer, integer, integer, integer, integer);
DROP FUNCTION get_report_context;
DROP FUNCTION profile_checkavail_statements_jit_stats;
DROP FUNCTION profile_checkavail_statements_temp_io_times;
DROP FUNCTION profile_checkavail_top_temp;
DROP FUNCTION profile_checkavail_stmt_wal_bytes;
DROP FUNCTION profile_checkavail_planning_times;
DROP FUNCTION profile_checkavail_sessionstats;
DROP FUNCTION profile_checkavail_io_times;
DROP FUNCTION profile_checkavail_tbl_top_dead;
DROP FUNCTION profile_checkavail_tbl_top_mods;
DROP FUNCTION profile_checkavail_functions;
DROP FUNCTION profile_checkavail_trg_functions;
DROP FUNCTION profile_checkavail_rusage;
DROP FUNCTION profile_checkavail_rusage_planstats;
DROP FUNCTION create_server_partitions;
DROP FUNCTION import_section_data_profile;

DROP FUNCTION top_statements;
DROP FUNCTION top_statements_format;
DROP FUNCTION top_statements_format_diff;
DROP FUNCTION wal_stats;
DROP FUNCTION wal_stats_format(integer, integer, integer, numeric);
DROP FUNCTION wal_stats_format(integer, integer, integer, integer, integer, numeric, numeric);
DROP FUNCTION calculate_wal_stats;
DROP FUNCTION collect_obj_stats;
DROP FUNCTION query_pg_stat_wal;
DROP FUNCTION sample_dbobj_delta;
DROP FUNCTION collect_pg_stat_statements_stats;
DROP FUNCTION save_pg_stat_statements;
DROP FUNCTION profile_checkavail_walstats;
DROP FUNCTION profile_checkavail_wal_stats_reset;
DROP FUNCTION collect_subsamples;
DROP FUNCTION import_section_data_subsample;
DROP FUNCTION take_subsample(integer, jsonb);
DROP FUNCTION delete_obsolete_samples;
DROP FUNCTION drop_server;
DROP FUNCTION take_sample(integer, boolean);
DROP FUNCTION top_indexes_format;
DROP FUNCTION delete_samples(integer, integer, integer);
DROP FUNCTION get_report_datasets;