{
 "title": "pg_profile activity",
 "description": "Dashboard based on subsample data",
 "tags": [ "pg_profile" ],
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 + 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   { "name": "database", "label": "Database name" },
   { "name": "app", "label": "Application" },
   { "name": "host" },
   { "name": "usename" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    },
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sessions by states",
   "type": "timeseries",
   "description": "Sessions by states observed in subsamples.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  subsample_ts as time,\n  sum(state_null) as \"Null\",\n  sum(active) as \"Active\",\n  sum(idle) as \"Idle\",\n  sum(idle_t) as \"Idle in xact\",\n  sum(idle_ta) as \"Idle in xact (aborted)\"\nFROM\n  sample_stat_activity_cnt sd\n  NATURAL JOIN session_attr sa\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid\n  AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n  AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n  AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n  AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\nGROUP BY subsample_ts\nUNION\nSELECT\n  subsample_ts as time,\n  sum(state_null) as \"Null\",\n  sum(active) as \"Active\",\n  sum(idle) as \"Idle\",\n  sum(idle_t) as \"Idle in xact\",\n  sum(idle_ta) as \"Idle in xact (aborted)\"\nFROM\n  last_stat_activity_count sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id = $endid\n  AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n  AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n  AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n  AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\nGROUP BY subsample_ts\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  subsample_ts as time,\n  sum(total) as \"Total\"\nFROM\n  sample_stat_activity_cnt sd\n  NATURAL JOIN session_attr sa\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY subsample_ts\nUNION\nSELECT\n  subsample_ts as time,\n  sum(total) as \"Total\"\nFROM\n  last_stat_activity_count sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id = $endid\nGROUP BY subsample_ts\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Sessions by waits",
   "type": "timeseries",
   "description": "Sessions by wait_event_types observed in subsamples.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  subsample_ts as time,\n  sum(activity) as \"Activity\",\n  sum(lwlock) as \"LWLock\",\n  sum(lock) as \"Lock\",\n  sum(buffer) as \"Buffer\",\n  sum(extension) as \"Extension\",\n  sum(client) as \"Client\",\n  sum(ipc) as \"IPC\",\n  sum(timeout) as \"Timeout\",\n  sum(io) as \"IO\"\nFROM\n  sample_stat_activity_cnt sd\n  NATURAL JOIN session_attr sa\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid\n  AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n  AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n  AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n  AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\nGROUP BY subsample_ts\nUNION\nSELECT\n  subsample_ts as time,\n  sum(activity) as \"Activity\",\n  sum(lwlock) as \"LWLock\",\n  sum(lock) as \"Lock\",\n  sum(buffer) as \"Buffer\",\n  sum(extension) as \"Extension\",\n  sum(client) as \"Client\",\n  sum(ipc) as \"IPC\",\n  sum(timeout) as \"Timeout\",\n  sum(io) as \"IO\"\nFROM\n  last_stat_activity_count sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id = $endid\n  AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n  AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n  AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n  AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\nGROUP BY subsample_ts\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT\n  subsample_ts as time,\n  sum(total) as \"Total\"\nFROM\n  sample_stat_activity_cnt sd\n  NATURAL JOIN session_attr sa\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY subsample_ts\nUNION\nSELECT\n  subsample_ts as time,\n  sum(total) as \"Total\"\nFROM\n  last_stat_activity_count sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND sd.sample_id = $endid\nGROUP BY subsample_ts\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Sessions by applications",
   "type": "piechart",
   "description": "Distribution of sessions observed in subsamples over the value of application_name attribute.\nClick on a segment will filter out other sessions.",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  application_name,\n  sample_data.sessions + coalesce(last_data.sessions, 0) AS sessions\nFROM (\n  SELECT\n    COALESCE(nullif(application_name, ''), 'N/A') AS application_name,\n    sum(total) AS sessions\n  FROM\n    sample_stat_activity_cnt sd\n    NATURAL JOIN session_attr sa\n  WHERE\n    sd.server_id = ${profile_servers}\n    AND sd.sample_id BETWEEN $startid + 1 AND $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY application_name\n  ) sample_data\n  LEFT JOIN (\n  SELECT\n    COALESCE(nullif(application_name, ''), 'N/A') AS application_name,\n    sum(total) AS sessions\n  FROM\n    last_stat_activity_count lsa\n  WHERE\n    lsa.server_id = ${profile_servers}\n    AND lsa.sample_id = $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY application_name\n  ) last_data\n  USING (application_name)\nORDER BY application_name"
    }
   ]
  },
  {
   "title": "Sessions by databases",
   "type": "piechart",
   "description": "Distribution of sessions observed in subsamples over the value of datname attribute.\nClick on a segment will filter out other sessions.",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datname AS \"Database\",\n  sample_data.sessions + coalesce(last_data.sessions, 0) AS sessions\nFROM (\n  SELECT\n    COALESCE(nullif(datname, ''), 'N/A') AS datname,\n    sum(total) AS sessions\n  FROM\n    sample_stat_activity_cnt sd\n    NATURAL JOIN session_attr sa\n  WHERE\n    sd.server_id = ${profile_servers}\n    AND sd.sample_id BETWEEN $startid + 1 AND $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY datname\n  ) sample_data\n  LEFT JOIN (\n  SELECT\n    COALESCE(nullif(datname, ''), 'N/A') AS datname,\n    sum(total) AS sessions\n  FROM\n    last_stat_activity_count lsa\n  WHERE\n    lsa.server_id = ${profile_servers}\n    AND lsa.sample_id = $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY datname\n  ) last_data\n  USING (datname)\nORDER BY datname"
    }
   ]
  },
  {
   "title": "Sessions by users",
   "type": "piechart",
   "description": "Distribution of sessions observed in subsamples over the value of usename attribute.\nClick on a segment will filter out other sessions.",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  usename AS \"User\",\n  sample_data.sessions + coalesce(last_data.sessions, 0) AS sessions\nFROM (\n  SELECT\n    COALESCE(nullif(usename, ''), 'N/A') AS usename,\n    sum(total) AS sessions\n  FROM\n    sample_stat_activity_cnt sd\n    NATURAL JOIN session_attr sa\n  WHERE\n    sd.server_id = ${profile_servers}\n    AND sd.sample_id BETWEEN $startid + 1 AND $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY usename\n  ) sample_data\n  LEFT JOIN (\n  SELECT\n    COALESCE(nullif(usename, ''), 'N/A') AS usename,\n    sum(total) AS sessions\n  FROM\n    last_stat_activity_count lsa\n  WHERE\n    lsa.server_id = ${profile_servers}\n    AND lsa.sample_id = $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY usename\n  ) last_data\n  USING (usename)\nORDER BY usename"
    }
   ]
  },
  {
   "title": "Sessions by hosts",
   "type": "piechart",
   "description": "Distribution of sessions observed in subsamples over the value of client_addr attribute.\nClick on a segment will filter out other sessions.",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  client_addr AS \"Client\",\n  sample_data.sessions + coalesce(last_data.sessions, 0) AS sessions\nFROM (\n  SELECT\n    COALESCE(nullif(client_addr::text, ''), 'N/A') AS client_addr,\n    sum(total) AS sessions\n  FROM\n    sample_stat_activity_cnt sd\n    NATURAL JOIN session_attr sa\n  WHERE\n    sd.server_id = ${profile_servers}\n    AND sd.sample_id BETWEEN $startid + 1 AND $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY client_addr\n  ) sample_data\n  LEFT JOIN (\n  SELECT\n    COALESCE(nullif(client_addr::text, ''), 'N/A') AS client_addr,\n    sum(total) AS sessions\n  FROM\n    last_stat_activity_count lsa\n  WHERE\n    lsa.server_id = ${profile_servers}\n    AND lsa.sample_id = $endid\n    AND (datname = '${database}' OR '${database}' = '' OR ('${database}' = 'N/A' AND nullif(datname,'') IS NULL))\n    AND (usename = '${usename}' OR '${usename}' = '' OR ('${usename}' = 'N/A' AND nullif(usename,'') IS NULL))\n    AND (application_name = '${app}' OR '${app}' = '' OR ('${app}' = 'N/A' AND nullif(application_name,'') IS NULL))\n    AND (client_addr::text = '${host}' OR '${host}' = '' OR ('${host}' = 'N/A' AND nullif(client_addr::text,'') IS NULL))\n  GROUP BY client_addr\n  ) last_data\n  USING (client_addr)\nORDER BY client_addr"
    }
   ]
  }
 ]
}